### ISSUE TITLE
Unknown error: Press "OK" to return to document list.

### ISSUE THREAD

**Issue by roboto-cloud** [ONLYOFFICE/docker-onlyoffice-owncloud#11]
### Hi, someone know how fix it?
I'm using traefik as loadbalancer, here an capture and my docker-compose.yml file:

### **log**
```
## document server (/var/log/onlyoffice/documentserver/nginx.error.log)
2017/11/11 14:11:56 [crit] 407#0: *108 connect() to [::1]:8080 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.19.0.3, server: , request: "GET /2017-10-28-08-40/spellchecker/doc/95_1510408155/c/info?t=1510409516194 HTTP/1.1", upstream: "http://[::1]:8080/doc/95_1510408155/c/info", host: "demo.nextcloud.com", referrer: "https://demo.nextcloud.com/ds-vpath/2017-10-28-08-40/web-apps/apps/documenteditor/main/index.html?_dc=2017-10-28-08-40&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor"

```
### **if I try do or change something on the admin area, get this message:**

`Error when trying to connect (Mixed Active Content is not allowed. HTTPS address for Document Server is required.) Nextcloud Search Basic settings Monitoring Sharing Security Theming Encryption Workflow Activity Usage survey Logging Additional settings Tips & tricks`

![screenshot from 2017-11-11 13-53-05](https://user-images.githubusercontent.com/32390825/32689941-411b50be-c6ee-11e7-9d84-d9c2772f3ae4.png)

```
version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

volumes:
  document_data:
  document_log:
  app_data:
  nextcloud-db-data:

services:
  app:
    restart: always
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    expose:
      - '80'
      - '9000'
    networks:
      - onlyoffice
    volumes:
      - app_data:/var/www/html
    networks:
      - proxy
      - internal
    labels:
      - traefik.enable=false

  onlyoffice-document-server:
    restart: always
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - proxy
      - internal
    labels:
      - traefik.docker.network=proxy

  nextcloud-db:
    image: postgres
    volumes:
      - nextcloud-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=nextcloud-db
    networks:
      - internal
    labels:
      - traefik.enable=false

  nginx:
    restart: always
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    expose:
    - '80'
    - '443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
    labels:
      - traefik.backend=demo.nextcloud.com
      - traefik.frontend.rule=Host:demo.nextcloud.com
      - traefik.docker.network=proxy
    networks:
      - internal
      - proxy

```
